In [3]:
import pandas as pd

df = pd.read_parquet('../rust-ingest/pcap_samples/ny4-small-10m_parsed.parquet')
df.shape

(10000000, 4)

In [4]:
df.head()

   packet_index  udp_payload_len  block_size  messages_in_block
0             0              108         108                  3
1             1               50          50                  1
2             2              166         166                  5
3             3               50          50                  1
4             4              108         108                  3

In [5]:
df.tail()

         packet_index  udp_payload_len  block_size  messages_in_block
9999995       9999995               50          50                  1
9999996       9999996               50          50                  1
9999997       9999997               50          50                  1
9999998       9999998               50          50                  1
9999999       9999999              138         138                  4

In [7]:
import pandas as pd

df = pd.read_parquet('../rust-ingest/pcap_samples/ny4-small-10k_trades.parquet')
df.shape

(14440, 19)

In [8]:
df.head()

,packet_index,block_sequence,block_timestamp_ns,message_index_in_block,participant,category,type_code,indicator,symbol_root,osi_symbol,bid,ask,bid_size,ask_size,price,size,side,action,flags
0,0,355512323,1692714599999800576,0,C,q,A,A,SPY,SPY 230830P00423000,0.48,0.50,310,418,NaN,NaN,None,None,418
1,0,355512323,1692714599999800576,1,C,q,A,A,SPY,SPY 230822P00439000,0.78,0.80,45,434,NaN,NaN,None,None,434
2,0,355512323,1692714599999800576,2,C,q,A,A,SPY,SPY 230825P00438000,2.25,2.28,121,193,NaN,NaN,None,None,193
3,1,207634110,1692714599999804416,0,C,q,A,A,SPY,SPY 240315C00455000,17.76,17.90,207,212,NaN,NaN,None,None,212
4,2,263110673,1692714599999802624,0,C,q,A,A,SPY,SPY 230823C00442000,0.92,0.94,350,52,NaN,NaN,None,None,52

In [9]:
df.tail()

,packet_index,block_sequence,block_timestamp_ns,message_index_in_block,participant,category,type_code,indicator,symbol_root,osi_symbol,bid,ask,bid_size,ask_size,price,size,side,action,flags
14435,9997,263119048,1692714600031779072,0,Q,q,,A,SPY,SPY 230828C00435000,6.62,6.67,6,70,NaN,NaN,None,None,70
14436,9998,207639644,1692714600031791104,0,H,q,,A,SPY,SPY 230929C00295000,145.12,146.31,44,44,NaN,NaN,None,None,44
14437,9998,207639644,1692714600031791104,1,Q,q,,A,SPY,SPY 230929C00329000,111.33,112.52,2,1,NaN,NaN,None,None,1
14438,9998,207639644,1692714600031791104,2,I,q,,A,SPY,SPY 230908C00447500,2.36,2.39,144,96,NaN,NaN,None,None,96
14439,9999,355521879,1692714600031791872,0,H,q,,A,SPY,SPY 230831P00467000,26.85,28.04,33,55,NaN,NaN,None,None,55